### ISSUE TITLE
TypeError: Cannot read property 'catch' of undefined

### ISSUE THREAD

**Issue by jabaa** [sindresorhus/bin-version-check#1]
I tried the example

```
const binVersionCheck = require('bin-version-check');

binVersionCheck('curl', '>=8').catch(err => {
        throw err;
        //=> 'InvalidBinVersion: curl 7.30.0 doesn't satisfy the version requirement of >=8'
});
```

but I got 

```
binVersionCheck('curl', '>=8').catch(err => {
                               ^

TypeError: Cannot read property 'catch' of undefined
    at Object.<anonymous> (/home/jabaa/Documents/Projects/Web/php/test.js:3:31)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by jabaa** [comment]
With

```
var binVersionCheck = require('bin-version-check');

binVersionCheck('php', '>=5.4', function () {});
```

I got 

```
/home/jabaa/Documents/Projects/Web/php/node_modules/semver-truncate/index.js:11
    version.build = '';
                  ^

TypeError: Cannot set property 'build' of null
    at module.exports (/home/jabaa/Documents/Projects/Web/php/node_modules/semver-truncate/index.js:11:16)
    at /home/jabaa/Documents/Projects/Web/php/node_modules/bin-version-check/index.js:20:25
    at /home/jabaa/Documents/Projects/Web/php/node_modules/bin-version/index.js:15:3
    at ChildProcess.exithandler (child_process.js:204:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by sindresorhus** [comment]
Are you sure you're using the latest version (3.0.0)?

**Comment by jabaa** [comment]
I installed gulp-connect-php and can't start it. While searching for the error I found that bin-version-checker didn't work. I updated it and bin-version-checker now works but gulp-connect-php doesn't. This issue can be closed.

**Comment by jabaa** [comment]
It's a problem with bin-version-check. In node_modules/gulp-connect-php/index.js you can comment out line 107 `binVersionCheck(options.bin, '>=5.4', function (err) {` and line 133 `}.bind(this));`. That's not really a solution but it temporarily works.
